# Generated by Django 3.2 on 2022-09-03 08:06

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='text',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='title',
        ),
        migrations.CreateModel(
            name='CarouselTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255)),
                ('paragraph', models.TextField(verbose_name='абзац')),
                ('text', models.TextField(verbose_name='текст')),
                ('image', models.ImageField(upload_to='Carousel/%Y/%m/%d')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.carousel')),
            ],
            options={
                'verbose_name': 'carousel Translation',
                'db_table': 'home_carousel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
