# Generated by Django 3.2 on 2022-09-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_carouseltranslation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouseltranslation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время создания'),
        ),
        migrations.AddField(
            model_name='carouseltranslation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время обновления'),
        ),
        migrations.AlterField(
            model_name='carouseltranslation',
            name='paragraph',
            field=models.TextField(verbose_name='Абзац'),
        ),
        migrations.AlterField(
            model_name='carouseltranslation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question',
            field=models.CharField(max_length=500, verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
    ]
