# Generated by Django 3.2 on 2022-09-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financing',
            options={'verbose_name': 'Финансирование', 'verbose_name_plural': 'Финансирования'},
        ),
        migrations.AlterModelOptions(
            name='financingtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Финансирование Translation'},
        ),
    ]
